# NOTE: update this with your service name
service: zansi-api
# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-export-env

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  stage: ${opt:stage, self:provider.stage}

  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
 
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  environment: ${file(env.yml):${self:custom.stage}, file(env.yml):default}
  
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  
  environment:
    tableName:
      Ref: OrdersTable
    
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem

      Resource:
        - "Fn::GetAtt": [OrdersTable, Arn]



functions:
  graphql:
    handler: graphql.graphqlHandler
    events:
      - http:
          path: ${self:provider.stage}/graphql
          method: post 
          cors: true
          integration: lambda-proxy
          

      - http:
          path: ${self:provider.stage}/graphql
          method: get 
          cors: true
          integration: lambda-proxy
          


resources:
  #DynamoDB
  - ${file(resources/dynamodb-table.yml)}
  #Cognito
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}




