# NOTE: update this with your service name
service: zansi-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:

  stage: ${opt:stage, self:provider.stage}
  #This will create two seperate tables for the different envs
  tableName: ${self:custom.stage}-notes
  #sets the read/write capacity
  tableThroughputs:
    prod:5
    default:1
  #this tells serverless to create the various throughputs for the two stages
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get 
          
resources:
  #DynamoDB
  - ${file(resources/dyanmodb-table.yml)}

